// Code generated by goctl. DO NOT EDIT.
package types

type PageReq struct {
	PageIndex int64 `form:"pageIndex,default=1"`
	PageSize  int64 `form:"pageSize,default=20"`
}

type Pagination struct {
	PageIndex int64 `json:"pageIndex"`
	PageSize  int64 `json:"pageSize"`
	Count     int64 `json:"count"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Uuid     string `json:"uuid"`
	Code     string `json:"code"`
}

type LoginResp struct {
	CurrentAuthority string `json:"currentAuthority"`
	Expire           int64  `json:"expire"`
	Token            string `json:"token"`
}

type CaptchaResp struct {
	Data string `json:"data"`
	Id   string `json:"id"`
}

type UserInfoResp struct {
	Introduction string   `json:"introduction"`
	Avatar       string   `json:"avatar"`
	UserName     string   `json:"userName"`
	UserId       int64    `json:"userId"`
	DeptId       int64    `json:"deptId"`
	Name         string   `json:"name"`
	Buttons      []string `json:"buttons"`
	Roles        []string `json:"roles"`
	Permissions  []string `json:"permissions"`
}

type UserListReq struct {
	PageReq
}

type UserListData struct {
	UserId    int64        `json:"userId"`
	UserName  string       `json:"username"`
	Phone     string       `json:"phone"`
	Status    int64        `json:"status"`
	Email     string       `json:"email"`
	Avatar    string       `json:"avatar"`
	Sex       int64        `json:"sex"`
	Remark    string       `json:"remark"`
	CreatedAt string       `json:"createdAt"`
	UpdatedAt string       `json:"updatedAt"`
	CreateBy  int64        `json:"createBy"`
	UpdateBy  int64        `json:"updateBy"`
	RoleId    int64        `json:"roleId"`
	DeptId    int64        `json:"deptId"`
	PostId    int64        `json:"postId"`
	Dept      DeptListData `json:"dept"`
}

type UserListResp struct {
	List []UserListData `json:"list"`
	Pagination
}

type UserAddReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
	Status   int64  `json:"status"`
	Email    string `json:"email"`
	Sex      int64  `json:"sex,optional"`
	Remark   string `json:"remark,optional"`
	RoleId   int64  `json:"roleId,optional"`
	DeptId   int64  `json:"deptId"`
	PostId   int64  `json:"postId,optional"`
	CreateBy int64  `json:"createBy,optional"`
	UpdateBy int64  `json:"updateBy,optional"`
}

type UserRetrieveReq struct {
	UserId int64 `path:"userId"`
}

type UserRetrieveResp struct {
	UserId   int64  `json:"userId"`
	Username string `json:"username"`
	Phone    string `json:"phone"`
	Status   int64  `json:"status"`
	Email    string `json:"email"`
	Sex      int64  `json:"sex"`
	Remark   string `json:"remark"`
	RoleId   int64  `json:"roleId"`
	DeptId   int64  `json:"deptId"`
	PostId   int64  `json:"postId"`
}

type UserUpdateReq struct {
	UserId   int64  `json:"userId"`
	Username string `json:"username"`
	Phone    string `json:"phone"`
	Status   int64  `json:"status"`
	Email    string `json:"email"`
	Sex      int64  `json:"sex,optional"`
	Remark   string `json:"remark,optional"`
	RoleId   int64  `json:"roleId,optional"`
	DeptId   int64  `json:"deptId"`
	PostId   int64  `json:"postId,optional"`
	UpdateBy int64  `json:"updateBy,optional"`
}

type UserUpdateStatusReq struct {
	UserId   int64 `json:"userId"`
	Status   int64 `json:"status"`
	UpdateBy int64 `json:"updateBy,optional"`
}

type UserUpdatePwdReq struct {
	UserId   int64  `json:"userId"`
	Password string `json:"password"`
	UpdateBy int64  `json:"updateBy,optional"`
}

type UserDeleteReq struct {
	Ids []int64 `json:"ids"`
}

type RoleListReq struct {
	PageReq
}

type RoleListData struct {
	RoleId    int64  `json:"roleId"`
	RoleName  string `json:"roleName"`
	RoleKey   string `json:"roleKey"`
	Sort      int64  `json:"sort"`
	Status    int64  `json:"status"`
	Remark    string `json:"remark"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	CreateBy  int64  `json:"createBy"`
	UpdateBy  int64  `json:"updateBy"`
}

type RoleListResp struct {
	List []RoleListData `json:"list"`
	Pagination
}

type RoleRetrieveReq struct {
	RoleId int64 `path:"roleId"`
}

type RoleRetrieveResp struct {
	RoleId   int64   `json:"roleId"`
	RoleName string  `json:"roleName"`
	RoleKey  string  `json:"roleKey"`
	Sort     int64   `json:"sort"`
	Status   int64   `json:"status"`
	Remark   string  `json:"remark"`
	MenuIds  []int64 `json:"menuIds"`
}

type RoleAddReq struct {
	RoleName string  `json:"roleName"`
	RoleKey  string  `json:"roleKey"`
	Sort     int64   `json:"sort"`
	Status   int64   `json:"status,optional"`
	Remark   string  `json:"remark,optional"`
	CreateBy int64   `json:"createBy,optional"`
	UpdateBy int64   `json:"updateBy,optional"`
	MenuIds  []int64 `json:"menuIds,optional"`
}

type RoleUpdateReq struct {
	RoleId   int64  `json:"roleId"`
	RoleName string `json:"roleName"`
	RoleKey  string `json:"roleKey"`
	Sort     int64  `json:"sort"`
	Status   int64  `json:"status,optional"`
	Remark   string `json:"remark,optional"`
	UpdateBy int64  `json:"updateBy,optional"`
}

type RoleDeleteReq struct {
	Ids []int64 `json:"ids"`
}

type RoleMenuTreeReq struct {
	RoleId int64 `path:"roleId"`
}

type RoleMenuTreeData struct {
	Id       int64              `json:"id"`
	Label    string             `json:"label"`
	Children []RoleMenuTreeData `json:"children"`
}

type RoleMenuTreeResp struct {
	Menus       []RoleMenuTreeData `json:"menus"`
	CheckedKeys []int64            `json:"checkedKeys"`
}

type DeptTreeResp struct {
	Id       int64          `json:"id"`
	Label    string         `json:"label"`
	Children []DeptTreeResp `json:"children"`
}

type DeptListData struct {
	DeptId    int64  `json:"deptId"`
	DeptPath  string `json:"deptPath"`
	DeptName  string `json:"deptName"`
	Phone     string `json:"phone"`
	Status    int64  `json:"status"`
	Email     string `json:"email"`
	Leader    string `json:"leader"`
	Sort      int64  `json:"sort"`
	ParentId  int64  `json:"parentId"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	CreateBy  int64  `json:"createBy"`
	UpdateBy  int64  `json:"updateBy"`
}

type DeptListResp struct {
	DeptId    int64          `json:"deptId"`
	DeptPath  string         `json:"deptPath"`
	DeptName  string         `json:"deptName"`
	Phone     string         `json:"phone"`
	Status    int64          `json:"status"`
	Email     string         `json:"email"`
	Leader    string         `json:"leader"`
	Sort      int64          `json:"sort"`
	ParentId  int64          `json:"parentId"`
	CreatedAt string         `json:"createdAt"`
	UpdatedAt string         `json:"updatedAt"`
	CreateBy  int64          `json:"createBy"`
	UpdateBy  int64          `json:"updateBy"`
	Children  []DeptListResp `json:"children"`
}

type DeptRetrieveReq struct {
	DeptId int64 `path:"deptId"`
}

type DeptRetrieveResp struct {
	DeptId   int64  `json:"deptId"`
	DeptName string `json:"deptName"`
	Phone    string `json:"phone"`
	Email    string `json:"email"`
	Leader   string `json:"leader"`
	Sort     int64  `json:"sort"`
	Status   int64  `json:"status"`
	ParentId int64  `json:"parentId"`
}

type DeptAddReq struct {
	DeptName string `json:"deptName"`
	Phone    string `json:"phone,optional"`
	Email    string `json:"email,optional"`
	Leader   string `json:"leader"`
	Sort     int64  `json:"sort,optional"`
	Status   int64  `json:"status,optional"`
	ParentId int64  `json:"parentId"`
	CreateBy int64  `json:"createBy,optional"`
	UpdateBy int64  `json:"updateBy,optional"`
}

type DeptUpdateReq struct {
	DeptId   int64  `json:"deptId"`
	DeptName string `json:"deptName"`
	Phone    string `json:"phone,optional"`
	Email    string `json:"email,optional"`
	Leader   string `json:"leader"`
	Sort     int64  `json:"sort,optional"`
	Status   int64  `json:"status,optional"`
	ParentId int64  `json:"parentId"`
	UpdateBy int64  `json:"updateBy,optional"`
}

type DeptDeleteReq struct {
	Ids []int64 `json:"ids"`
}

type SysConfigResp struct {
	SysAppName string `json:"sys_app_name"`
	SysAppLogo string `json:"sys_app_logo"`
}

type ConfigPwReq struct {
	ConfigKey string `path:"configKey"`
}

type ConfigPwResp struct {
	ConfigKey   string `json:"configKey"`
	ConfigValue string `json:"configValue"`
}

type ConfigListReq struct {
	PageReq
}

type ConfigListData struct {
	Id          int64  `json:"id"`
	ConfigName  string `json:"configName"`
	ConfigKey   string `json:"configKey"`
	ConfigValue string `json:"configValue"`
	ConfigType  int64  `json:"configType"`
	IsFrontend  int64  `json:"isFrontend"`
	Remark      string `json:"remark"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
	CreateBy    int64  `json:"createBy"`
	UpdateBy    int64  `json:"updateBy"`
}

type ConfigListResp struct {
	List []ConfigListData `json:"list"`
	Pagination
}

type ConfigRetrieveReq struct {
	Id int64 `path:"id"`
}

type ConfigRetrieveResp struct {
	Id          int64  `json:"id"`
	ConfigName  string `json:"configName"`
	ConfigKey   string `json:"configKey"`
	ConfigValue string `json:"configValue"`
	ConfigType  int64  `json:"configType"`
	IsFrontend  int64  `json:"isFrontend"`
	Remark      string `json:"remark"`
}

type ConfigAddReq struct {
	ConfigName  string `json:"configName"`
	ConfigKey   string `json:"configKey"`
	ConfigValue string `json:"configValue"`
	ConfigType  int64  `json:"configType"`
	IsFrontend  int64  `json:"isFrontend"`
	Remark      string `json:"remark,optional"`
	CreateBy    int64  `json:"createBy,optional"`
	UpdateBy    int64  `json:"updateBy,optional"`
}

type ConfigUpdateReq struct {
	Id          int64  `json:"id"`
	ConfigName  string `json:"configName"`
	ConfigKey   string `json:"configKey"`
	ConfigValue string `json:"configValue"`
	ConfigType  int64  `json:"configType"`
	IsFrontend  int64  `json:"isFrontend"`
	Remark      string `json:"remark"`
	UpdateBy    int64  `json:"updateBy,optional"`
}

type ConfigDeleteReq struct {
	Ids []int64 `json:"ids"`
}

type MenuRoleResp struct {
	MenuId     int64          `json:"menuId"`
	MenuName   string         `json:"menuName"`
	MenuType   string         `json:"menuType"`
	Title      string         `json:"title"`
	Permission string         `json:"permission"`
	Params     string         `json:"params"`
	Path       string         `json:"path"`
	Paths      string         `json:"paths"`
	Action     string         `json:"action"`
	Apis       string         `json:"apis"`
	SysApi     string         `json:"sysApi"`
	Breadcrumb string         `json:"breadcrumb"`
	Component  string         `json:"component"`
	ParentId   int64          `json:"parentId"`
	Sort       int64          `json:"sort"`
	DataScope  string         `json:"dataScope"`
	Icon       string         `json:"icon"`
	IsFrame    string         `json:"isFrame"`
	Visible    string         `json:"visible"`
	Is_select  bool           `json:"is_select"`
	NoCache    int64          `json:"noCache"`
	CreateBy   int64          `json:"createBy"`
	CreatedAt  string         `json:"createdAt"`
	UpdateBy   int64          `json:"updateBy"`
	UpdatedAt  string         `json:"updatedAt"`
	Children   []MenuRoleResp `json:"children"`
}

type MenuListData struct {
	MenuId     int64  `json:"menuId"`
	MenuName   string `json:"menuName"`
	MenuType   string `json:"menuType"`
	Title      string `json:"title"`
	Permission string `json:"permission"`
	Params     string `json:"params"`
	Path       string `json:"path"`
	Paths      string `json:"paths"`
	Action     string `json:"action"`
	Apis       string `json:"apis"`
	SysApi     string `json:"sysApi"`
	Breadcrumb string `json:"breadcrumb"`
	Component  string `json:"component"`
	ParentId   int64  `json:"parentId"`
	Sort       int64  `json:"sort"`
	DataScope  string `json:"dataScope"`
	Icon       string `json:"icon"`
	IsFrame    string `json:"isFrame"`
	Visible    string `json:"visible"`
	Is_select  bool   `json:"is_select"`
	NoCache    int64  `json:"noCache"`
	CreateBy   int64  `json:"createBy"`
	CreatedAt  string `json:"createdAt"`
	UpdateBy   int64  `json:"updateBy"`
	UpdatedAt  string `json:"updatedAt"`
}

type MenuListResp struct {
	MenuId     int64          `json:"menuId"`
	MenuName   string         `json:"menuName"`
	MenuType   string         `json:"menuType"`
	Title      string         `json:"title"`
	Permission string         `json:"permission"`
	Params     string         `json:"params"`
	Path       string         `json:"path"`
	Paths      string         `json:"paths"`
	Action     string         `json:"action"`
	Apis       string         `json:"apis"`
	SysApi     string         `json:"sysApi"`
	Breadcrumb string         `json:"breadcrumb"`
	Component  string         `json:"component"`
	ParentId   int64          `json:"parentId"`
	Sort       int64          `json:"sort"`
	DataScope  string         `json:"dataScope"`
	Icon       string         `json:"icon"`
	IsFrame    string         `json:"isFrame"`
	Visible    string         `json:"visible"`
	Is_select  bool           `json:"is_select"`
	NoCache    int64          `json:"noCache"`
	CreateBy   int64          `json:"createBy"`
	CreatedAt  string         `json:"createdAt"`
	UpdateBy   int64          `json:"updateBy"`
	UpdatedAt  string         `json:"updatedAt"`
	Children   []MenuListResp `json:"children"`
}

type MenuRetrieveReq struct {
	MenuId int64 `path:"menuId"`
}

type MenuRetrieveResp struct {
	MenuId     int64  `json:"menuId"`
	MenuName   string `json:"menuName"`
	MenuType   string `json:"menuType"`
	Title      string `json:"title"`
	Permission string `json:"permission"`
	Params     string `json:"params"`
	Path       string `json:"path"`
	Paths      string `json:"paths"`
	Action     string `json:"action"`
	Apis       string `json:"apis"`
	SysApi     string `json:"sysApi"`
	Breadcrumb string `json:"breadcrumb"`
	Component  string `json:"component"`
	ParentId   int64  `json:"parentId"`
	Sort       int64  `json:"sort"`
	DataScope  string `json:"dataScope"`
	Icon       string `json:"icon"`
	IsFrame    string `json:"isFrame"`
	Visible    string `json:"visible"`
	Is_select  bool   `json:"is_select"`
	NoCache    int64  `json:"noCache"`
}

type MenuAddReq struct {
	MenuName   string `json:"menuName"`
	MenuType   string `json:"menuType"`
	Title      string `json:"title"`
	Permission string `json:"permission"`
	Params     string `json:"params,optional"`
	Path       string `json:"path,optional"`
	Paths      string `json:"paths,optional"`
	Action     string `json:"action,optional"`
	Breadcrumb string `json:"breadcrumb,optional"`
	Component  string `json:"component,optional"`
	ParentId   int64  `json:"parentId,optional"`
	Sort       int64  `json:"sort"`
	Icon       string `json:"icon"`
	IsFrame    string `json:"isFrame,optional"`
	Visible    string `json:"visible"`
	NoCache    int64  `json:"noCache,optional"`
	CreateBy   int64  `json:"createBy,optional"`
	UpdateBy   int64  `json:"updateBy,optional"`
}

type MenuUpdateReq struct {
	MenuId     int64  `json:"menuId"`
	MenuName   string `json:"menuName"`
	MenuType   string `json:"menuType"`
	Title      string `json:"title"`
	Permission string `json:"permission"`
	Params     string `json:"params"`
	Path       string `json:"path"`
	Paths      string `json:"paths"`
	Action     string `json:"action"`
	Apis       string `json:"apis"`
	SysApi     string `json:"sysApi"`
	Breadcrumb string `json:"breadcrumb"`
	Component  string `json:"component"`
	ParentId   int64  `json:"parentId"`
	Sort       int64  `json:"sort"`
	DataScope  string `json:"dataScope"`
	Icon       string `json:"icon"`
	IsFrame    string `json:"isFrame"`
	Visible    string `json:"visible"`
	Is_select  bool   `json:"is_select"`
	NoCache    int64  `json:"noCache"`
	UpdateBy   int64  `json:"updateBy,optional"`
}

type MenuDeleteReq struct {
	MenuId int64 `json:"menuId"`
}

type DictDataOpReq struct {
	DictType string `form:"dictType"`
}

type DictDataOpResp struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

type DictDataListReq struct {
	PageReq
	DictType string `form:"dictType"`
}

type DictDataListData struct {
	DictId    int64  `json:"dictId"`
	DictLabel string `json:"dictLabel"`
	DictValue string `json:"dictValue"`
	DictType  string `json:"dictType"`
	DictSort  int64  `json:"dictSort"`
	Status    int64  `json:"status"`
	Remark    string `json:"remark"`
	CreatedAt string `json:"createdAt"`
}

type DictDataListResp struct {
	List []DictDataListData `json:"list"`
	Pagination
}

type DictDataRetrieveReq struct {
	DictId int64 `path:"dictId"`
}

type DictDataRetrieveResp struct {
	DictId    int64  `json:"dictId"`
	DictLabel string `json:"dictLabel"`
	DictValue string `json:"dictValue"`
	DictType  string `json:"dictType"`
	DictSort  int64  `json:"dictSort"`
	Status    int64  `json:"status"`
	Remark    string `json:"remark"`
}

type DictDataAddReq struct {
	DictLabel string `json:"dictLabel"`
	DictValue string `json:"dictValue"`
	DictType  string `json:"dictType"`
	DictSort  int64  `json:"dictSort"`
	Status    int64  `json:"status,optional"`
	Remark    string `json:"remark,optional"`
	CreateBy  int64  `json:"createBy,optional"`
	UpdateBy  int64  `json:"updateBy,optional"`
}

type DictDataUpdateReq struct {
	DictId    int64  `json:"dictId"`
	DictLabel string `json:"dictLabel"`
	DictValue string `json:"dictValue"`
	DictType  string `json:"dictType"`
	DictSort  int64  `json:"dictSort"`
	Status    int64  `json:"status,optional"`
	Remark    string `json:"remark,optional"`
	UpdateBy  int64  `json:"updateBy,optional"`
}

type DictDataDeleteReq struct {
	Ids []int64 `json:"ids"`
}

type DictTypeListReq struct {
	PageReq
}

type DictTypeListData struct {
	DictId    int64  `json:"dictId"`
	DictName  string `json:"dictName"`
	DictType  string `json:"dictType"`
	Status    int64  `json:"status"`
	Remark    string `json:"remark"`
	CreatedAt string `json:"createdAt"`
}

type DictTypeListResp struct {
	List []DictTypeListData `json:"list"`
	Pagination
}

type DictTypeRetrieveReq struct {
	DictId int64 `path:"dictId"`
}

type DictTypeRetrieveResp struct {
	DictId   int64  `json:"dictId"`
	DictName string `json:"dictName"`
	DictType string `json:"dictType"`
	Status   int64  `json:"status"`
	Remark   string `json:"remark"`
}

type DictTypeAddReq struct {
	DictName string `json:"dictName"`
	DictType string `json:"dictType"`
	Status   int64  `json:"status,optional"`
	Remark   string `json:"remark,optional"`
	CreateBy int64  `json:"createBy,optional"`
	UpdateBy int64  `json:"updateBy,optional"`
}

type DictTypeUpdateReq struct {
	DictId   int64  `json:"dictId"`
	DictName string `json:"dictName"`
	DictType string `json:"dictType"`
	Status   int64  `json:"status,optional"`
	Remark   string `json:"remark,optional"`
	UpdateBy int64  `json:"updateBy,optional"`
}

type DictTypeDeleteReq struct {
	Ids []int64 `json:"ids"`
}

type PostListReq struct {
	PageReq
}

type PostListData struct {
	PostId    int64  `json:"postId"`
	PostName  string `json:"postName"`
	PostCode  string `json:"postCode"`
	Sort      int64  `json:"sort"`
	Status    int64  `json:"status"`
	Remark    string `json:"remark"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	CreateBy  int64  `json:"createBy"`
	UpdateBy  int64  `json:"updateBy"`
}

type PostListResp struct {
	List []PostListData `json:"list"`
	Pagination
}

type PostRetrieveReq struct {
	PostId int64 `path:"postId"`
}

type PostRetrieveResp struct {
	PostId   int64  `json:"postId"`
	PostName string `json:"postName"`
	PostCode string `json:"postCode"`
	Sort     int64  `json:"sort"`
	Status   int64  `json:"status"`
	Remark   string `json:"remark"`
}

type PostAddReq struct {
	PostName string `json:"postName"`
	PostCode string `json:"postCode"`
	Sort     int64  `json:"sort"`
	Status   int64  `json:"status,optional"`
	Remark   string `json:"remark,optional"`
	CreateBy int64  `json:"createBy,optional"`
	UpdateBy int64  `json:"updateBy,optional"`
}

type PostUpdateReq struct {
	PostId   int64  `json:"postId"`
	PostName string `json:"postName"`
	PostCode string `json:"postCode"`
	Sort     int64  `json:"sort"`
	Status   int64  `json:"status,optional"`
	Remark   string `json:"remark,optional"`
	UpdateBy int64  `json:"updateBy,optional"`
}

type PostDeleteReq struct {
	Ids []int64 `json:"ids"`
}
