// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Uuid     string `json:"uuid"`
	Code     string `json:"code"`
}

type LoginResponse struct {
	Code             int64  `json:"code"`
	Success          bool   `json:"success"`
	CurrentAuthority string `json:"currentAuthority"`
	Expire           int64  `json:"expire"`
	Token            string `json:"token"`
}

type CaptchaResponse struct {
	Code int64  `json:"code"`
	Data string `json:"data"`
	Id   string `json:"id"`
	Msg  string `json:"msg"`
}

type UserInfo struct {
	Introduction string   `json:"introduction"`
	Avatar       string   `json:"avatar"`
	UserName     string   `json:"userName"`
	UserId       int64    `json:"userId"`
	DeptId       int64    `json:"deptId"`
	Name         string   `json:"name"`
	Buttons      []string `json:"buttons"`
	Roles        []string `json:"roles"`
	Permissions  []string `json:"permissions"`
}

type UserInfoResponse struct {
	Code int64    `json:"code"`
	Data UserInfo `json:"data"`
}

type SysConfigResp struct {
	Code int64             `json:"code"`
	Data map[string]string `json:"data"`
	Msg  string            `json:"msg"`
}
