// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysDeptFieldNames          = builder.RawFieldNames(&SysDept{})
	sysDeptRows                = strings.Join(sysDeptFieldNames, ",")
	sysDeptRowsExpectAutoSet   = strings.Join(stringx.Remove(sysDeptFieldNames, "`dept_id`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`", "`create_time`"), ",")
	sysDeptRowsWithPlaceHolder = strings.Join(stringx.Remove(sysDeptFieldNames, "`dept_id`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`", "`create_time`"), "=?,") + "=?"

	cacheSysDeptDeptIdPrefix = "cache:sysDept:deptId:"
)

type (
	sysDeptModel interface {
		Insert(ctx context.Context, data *SysDept) (sql.Result, error)
		FindOne(ctx context.Context, deptId int64) (*SysDept, error)
		Update(ctx context.Context, data *SysDept) error
		Delete(ctx context.Context, deptId int64) error
	}

	defaultSysDeptModel struct {
		sqlc.CachedConn
		table string
	}

	SysDept struct {
		DeptId    int64          `db:"dept_id"`
		ParentId  sql.NullInt64  `db:"parent_id"`
		DeptPath  string         `db:"dept_path"`
		DeptName  sql.NullString `db:"dept_name"`
		Sort      sql.NullInt64  `db:"sort"`
		Leader    sql.NullString `db:"leader"`
		Phone     sql.NullString `db:"phone"`
		Email     sql.NullString `db:"email"`
		Status    sql.NullInt64  `db:"status"`
		CreateBy  sql.NullInt64  `db:"create_by"`  // 创建者
		UpdateBy  sql.NullInt64  `db:"update_by"`  // 更新者
		CreatedAt sql.NullTime   `db:"created_at"` // 创建时间
		UpdatedAt sql.NullTime   `db:"updated_at"` // 最后更新时间
		DeletedAt sql.NullTime   `db:"deleted_at"` // 删除时间
	}
)

func newSysDeptModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultSysDeptModel {
	return &defaultSysDeptModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`sys_dept`",
	}
}

func (m *defaultSysDeptModel) Delete(ctx context.Context, deptId int64) error {
	sysDeptDeptIdKey := fmt.Sprintf("%s%v", cacheSysDeptDeptIdPrefix, deptId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `dept_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, deptId)
	}, sysDeptDeptIdKey)
	return err
}

func (m *defaultSysDeptModel) FindOne(ctx context.Context, deptId int64) (*SysDept, error) {
	sysDeptDeptIdKey := fmt.Sprintf("%s%v", cacheSysDeptDeptIdPrefix, deptId)
	var resp SysDept
	err := m.QueryRowCtx(ctx, &resp, sysDeptDeptIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `dept_id` = ? limit 1", sysDeptRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, deptId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDeptModel) Insert(ctx context.Context, data *SysDept) (sql.Result, error) {
	sysDeptDeptIdKey := fmt.Sprintf("%s%v", cacheSysDeptDeptIdPrefix, data.DeptId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysDeptRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ParentId, data.DeptPath, data.DeptName, data.Sort, data.Leader, data.Phone, data.Email, data.Status, data.CreateBy, data.UpdateBy, data.DeletedAt)
	}, sysDeptDeptIdKey)
	return ret, err
}

func (m *defaultSysDeptModel) Update(ctx context.Context, data *SysDept) error {
	sysDeptDeptIdKey := fmt.Sprintf("%s%v", cacheSysDeptDeptIdPrefix, data.DeptId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `dept_id` = ?", m.table, sysDeptRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ParentId, data.DeptPath, data.DeptName, data.Sort, data.Leader, data.Phone, data.Email, data.Status, data.CreateBy, data.UpdateBy, data.DeletedAt, data.DeptId)
	}, sysDeptDeptIdKey)
	return err
}

func (m *defaultSysDeptModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheSysDeptDeptIdPrefix, primary)
}

func (m *defaultSysDeptModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `dept_id` = ? limit 1", sysDeptRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysDeptModel) tableName() string {
	return m.table
}
