// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysPostFieldNames          = builder.RawFieldNames(&SysPost{})
	sysPostRows                = strings.Join(sysPostFieldNames, ",")
	sysPostRowsExpectAutoSet   = strings.Join(stringx.Remove(sysPostFieldNames, "`post_id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), ",")
	sysPostRowsWithPlaceHolder = strings.Join(stringx.Remove(sysPostFieldNames, "`post_id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), "=?,") + "=?"

	cacheSysPostPostIdPrefix = "cache:sysPost:postId:"
)

type (
	sysPostModel interface {
		Insert(ctx context.Context, data *SysPost) (sql.Result, error)
		FindOne(ctx context.Context, postId int64) (*SysPost, error)
		Update(ctx context.Context, data *SysPost) error
		Delete(ctx context.Context, postId int64) error
	}

	defaultSysPostModel struct {
		sqlc.CachedConn
		table string
	}

	SysPost struct {
		PostId    int64          `db:"post_id"`
		PostName  sql.NullString `db:"post_name"`
		PostCode  sql.NullString `db:"post_code"`
		Sort      sql.NullInt64  `db:"sort"`
		Status    sql.NullInt64  `db:"status"`
		Remark    sql.NullString `db:"remark"`
		CreateBy  sql.NullInt64  `db:"create_by"`  // 创建者
		UpdateBy  sql.NullInt64  `db:"update_by"`  // 更新者
		CreatedAt sql.NullTime   `db:"created_at"` // 创建时间
		UpdatedAt sql.NullTime   `db:"updated_at"` // 最后更新时间
		DeletedAt sql.NullTime   `db:"deleted_at"` // 删除时间
	}
)

func newSysPostModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultSysPostModel {
	return &defaultSysPostModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`sys_post`",
	}
}

func (m *defaultSysPostModel) Delete(ctx context.Context, postId int64) error {
	sysPostPostIdKey := fmt.Sprintf("%s%v", cacheSysPostPostIdPrefix, postId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `post_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, postId)
	}, sysPostPostIdKey)
	return err
}

func (m *defaultSysPostModel) FindOne(ctx context.Context, postId int64) (*SysPost, error) {
	sysPostPostIdKey := fmt.Sprintf("%s%v", cacheSysPostPostIdPrefix, postId)
	var resp SysPost
	err := m.QueryRowCtx(ctx, &resp, sysPostPostIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `post_id` = ? limit 1", sysPostRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, postId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysPostModel) Insert(ctx context.Context, data *SysPost) (sql.Result, error) {
	sysPostPostIdKey := fmt.Sprintf("%s%v", cacheSysPostPostIdPrefix, data.PostId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysPostRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.PostName, data.PostCode, data.Sort, data.Status, data.Remark, data.CreateBy, data.UpdateBy, data.DeletedAt)
	}, sysPostPostIdKey)
	return ret, err
}

func (m *defaultSysPostModel) Update(ctx context.Context, data *SysPost) error {
	sysPostPostIdKey := fmt.Sprintf("%s%v", cacheSysPostPostIdPrefix, data.PostId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `post_id` = ?", m.table, sysPostRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.PostName, data.PostCode, data.Sort, data.Status, data.Remark, data.CreateBy, data.UpdateBy, data.DeletedAt, data.PostId)
	}, sysPostPostIdKey)
	return err
}

func (m *defaultSysPostModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheSysPostPostIdPrefix, primary)
}

func (m *defaultSysPostModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `post_id` = ? limit 1", sysPostRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysPostModel) tableName() string {
	return m.table
}
